
language: java

dist: trusty
sudo: false

branches:
  only:
    - master
    - develop

env:
  global:
    - TRAVIS_ENV=true
    - secure: "ZPk3ZNPSu2bNnuefWRvA8H/HvdcWmakCUp2oKVN5JT9KPe/N5yrNDAlFHqzvElYhCIOd7LdXfKMbWyVeLY/zM4nMJdz2iq0M56xU/bCaE3AB7CQIComlpjqWvifhhFi8NtUGI02A7XlnJKl0+CZDQfH9PiVL33VUktrtNswSYfch6zI5LauK5IrKtetACtFFr/WMXTTjUGBZl9hSBs9ouYi2MhX6oqmvDayAdm7wR0E70ib/clAtMQR+iDHMaU0ZgCdND8fDtyfc8vlcr/9DShJ80bIZprPk8UbmiJlk8l/amoE/5WLTJwR0533WLA/O/KTr6b/ummFBy7mWvitkYgz6VeDKZ5C0cRVVHkIsfClKHLiaGDxpzIpL3RaI7JhsQYcPWegvOjdvbAtKUBnWMBkYqD+GxcpG6AJfBbR2h8Gw4PwENCU3J/SX7YBkMJHfmgy/CZ+ECL2BpKNsHz9KUXNTzc5WV3u3eI5jvWHDUUwfY3Y4msyNoZY/TRbu1Ys4etA/LDoBhFjcawqZWixzgpK07w5dnF2/XGBu3mRzqnhiAqzgXrXR9vRc4lmLkOxtdm/pMLz8INY32eB/7MmkKFk7+4sRcwMbYuv6TbOoev8ibN9e/Yy2ehzwRkVbxGSkgiMN2lzLnXHAtAInXPLwx0z1Vz/FSGUdrXx11aFF9UM="

before_install:
 - chmod +x ./gradlew
# - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && chmod +x ./install-jdk.sh
 - chmod +x ./install-jdk.sh
 - chmod +x ./.travis.default-compile.sh
 - chmod +x ./.travis.default-test.sh

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

after_script:
 - ./gradlew test jacocoTestReport -x compileJava
 - JACOCO_SOURCE_PATH=foundation/src/main/java
   ./cc-test-reporter format-coverage ./foundation/build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
 - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
#  OpenJDK default
    - stage: OpenJDK General-Availability Releases
      env:    TEST_DUMMY_INFO="compile:openjdk8, test:openjdk8"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && jdk_switcher use openjdk8
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk8"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && jdk_switcher use openjdk8
              && ./.travis.default-test.sh

#  OpenJDK install
    - stage: jdk.java.net - Archived OpenJDK General-Availability Releases
      env:    TEST_DUMMY_INFO="compile:openjdk8, test:openjdk9"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 9 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk9"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 9 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:openjdk8, test:openjdk10"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 10 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk10"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 10 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:openjdk8, test:openjdk11"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 11 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk11"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 11 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

#  OracleJDK default
    - stage: ☕ JDK builds, from Oracle
      env:    TEST_DUMMY_INFO="compile:openjdk8, test:oraclejdk8"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && jdk_switcher use oraclejdk8
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk8"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && jdk_switcher use oraclejdk8
              && ./.travis.default-test.sh

#  OracleJDK install
    - stage: ☕ jdk.java.net - JDK builds, from Oracle
      env:    TEST_DUMMY_INFO="compile:openjdk8, test:oraclejdk12"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 12 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk12"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 12 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:openjdk8, test:oraclejdk13"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 13 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk13"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 13 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:openjdk8, test:oraclejdk14"
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 14 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk14"
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -F 14 -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

#  OracleJDK install, OS mac
    - stage: ☕ jdk.java.net - JDK builds, from Oracle: OS -  mac
    - env:    TEST_DUMMY_INFO="compile:openjdk8, test:oraclejdk-ea"
      os:     osx
      script: jdk_switcher use openjdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -V -F ea -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

    - env:    TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk-ea"
      os:     osx
      script: jdk_switcher use oraclejdk8
              && ./.travis.default-compile.sh
              && export JAVA_HOME=`./install-jdk.sh -V -F ea -E | tail -n 1`
              && export PATH=${JAVA_HOME}/bin:$PATH
              && ./.travis.default-test.sh

