language: groovy
before_install:
 - chmod +x gradlew
branches:
  only:
    - master
    - develop
env:
  global:
    TRAVIS_ENV=true
jdk:
  - openjdk8
  - oraclejdk8
script:
  - # test script
  - jdk_switcher use openjdk8
  - ./gradlew check --stacktrace --info
  - jdk_switcher use openjdk10
  - ./gradlew check --stacktrace --info
  - jdk_switcher use openjdk11
  - ./gradlew check --stacktrace --info
  - jdk_switcher use oraclejdk8
  - ./gradlew check --stacktrace --info
  - jdk_switcher use oraclejdk11
  - ./gradlew check --stacktrace --info

