language: groovy
before_install:
 - chmod +x ./gradlew
# - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && chmod +x ./install-jdk.sh
 - chmod +x ./install-jdk.sh
branches:
  only:
    - master
    - develop
env:
  global:
    TRAVIS_ENV=true
jdk:
  - openjdk8
  - oraclejdk8
matrix:
  include:
    - script:
      - jdk_switcher use oraclejdk8
      - echo $JAVA_HOME ; javac -version ; java -version
      - ./gradlew assemble --stacktrace --info
      - jdk_switcher use openjdk8
      - echo $JAVA_HOME ; javac -version ; java -version
      - ./gradlew check --stacktrace --info
    - script:
      - jdk_switcher use openjdk8
      - echo $JAVA_HOME ; javac -version ; java -version
      - ./gradlew assemble --stacktrace --info
      - export _JAVA_OPTIONS=
      - mkdir -p ${HOME}/tmp
#      - export JAVA_HOME=${HOME}/tmp/jdk11 && export PATH=${JAVA_HOME}/bin:$PATH
      - JAVA_HOME=`./install-jdk.sh -F 11 -W ${HOME}/tmp -E | tail -n 1`
      - PATH=${JAVA_HOME}/bin:$PATH
      - echo $HOME
      - echo $JAVA_HOME ; javac -version ; java -version
      - echo $PATH
      - pwd ; ls -al `pwd`
      - ./gradlew check --stacktrace --info
#matrix:
#  include:
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 8(OpenJDK) ============================================================================="
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - jdk_switcher use openjdk8
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 9(OpenJDK) ============================================================================="
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ./install-jdk.sh -F 9
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 10(OpenJDK) ============================================================================"
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ./install-jdk.sh -F 10
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 11(OpenJDK) ============================================================================"
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ./install-jdk.sh -F 11
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 8(OracleJDK) ==========================================================================="
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - jdk_switcher use oraclejdk8
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 10(OracleJDK) =========================================================================="
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ./install-jdk.sh -F 10 -L BCL
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#    - jdk:
#        - openjdk8
#        - oraclejdk8
#      script:
#        - echo "test using JDK 11(OracleJDK) =========================================================================="
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ./install-jdk.sh -F 11 -L BCL
#        - javac -version ; java -version ; echo $JAVA_HOME
#        - ls -al
#        - ./gradlew check --stacktrace --info
#
