language: groovy
before_install:
 - chmod +x ./gradlew
# - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && chmod +x ./install-jdk.sh
 - chmod +x ./install-jdk.sh
 - chmod +x ./.travis.default-compile.sh
 - chmod +x ./.travis.default-test.sh
 - chmod +x ./.travis.openjdk9-test.sh
 - chmod +x ./.travis.openjdk10-test.sh
 - chmod +x ./.travis.openjdk11-test.sh
 - chmod +x ./.travis.oraclejdk10-test.sh
 - chmod +x ./.travis.oraclejdk11-test.sh
branches:
  only:
    - master
    - develop
env:
  global:
    - TRAVIS_ENV=true
jdk:
  - openjdk8
  - oraclejdk8
matrix:
  include:
# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:openjdk8"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && jdk_switcher use openjdk8 && ./.travis.default-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk8"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && jdk_switcher use openjdk8 && ./.travis.default-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:openjdk9"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && ./.travis.openjdk9-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk9"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && ./.travis.openjdk9-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:openjdk10"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && ./.travis.openjdk10-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk10"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && ./.travis.openjdk10-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:openjdk11"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && ./.travis.openjdk11-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:openjdk11"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && ./.travis.openjdk11-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:oraclejdk8"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && jdk_switcher use oraclejdk8 && ./.travis.default-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk8"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && jdk_switcher use oraclejdk8 && ./.travis.default-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:oraclejdk10"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && ./.travis.oraclejdk10-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk10"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && ./.travis.oraclejdk10-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:openjdk8,   test:oraclejdk11"
      script:
      - jdk_switcher use openjdk8 && ./.travis.default-compile.sh && ./.travis.oraclejdk11-test.sh

# ===============================================================
    - env: TEST_DUMMY_INFO="compile:oraclejdk8, test:oraclejdk11"
      script:
      - jdk_switcher use oraclejdk8 && ./.travis.default-compile.sh && ./.travis.oraclejdk11-test.sh

