language: groovy
before_install:
 - chmod +x gradlew
 - chmod +x .test.sh
branches:
  only:
    - master
    - develop
env:
  global:
    TRAVIS_ENV=true
script: ./.test.sh
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
