language: groovy
before_install:
 - chmod +x ./gradlew
# - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && chmod +x ./install-jdk.sh
 - chmod +x ./install-jdk.sh
 - chmod +x ./.travis.default-test.sh
 - chmod +x ./.travis.openjdk9-test.sh
 - chmod +x ./.travis.openjdk10-test.sh
 - chmod +x ./.travis.openjdk11-test.sh
 - chmod +x ./.travis.oraclejdk10-test.sh
 - chmod +x ./.travis.oraclejdk11-test.sh
branches:
  only:
    - master
    - develop
env:
  global:
    - TRAVIS_ENV=true
jdk:
  - openjdk8
  - oraclejdk8
matrix:
  include:
    - script:
      - ./.travis.default-test.sh openjdk8 oraclejdk8
    - script:
      - ./.travis.default-test.sh oraclejdk8 openjdk8
    - script:
      - ./.travis.openjdk9-test.sh openjdk8
    - script:
      - ./.travis.openjdk9-test.sh oraclejdk8
    - script:
      - ./.travis.openjdk10-test.sh openjdk8
    - script:
      - ./.travis.openjdk10-test.sh oraclejdk8
    - script:
      - ./.travis.openjdk11-test.sh openjdk8
    - script:
      - ./.travis.openjdk11-test.sh oraclejdk8
    - script:
      - ./.travis.oraclejdk10-test.sh openjdk8
    - script:
      - ./.travis.oraclejdk10-test.sh oraclejdk8
    - script:
      - ./.travis.oraclejdk11-test.sh openjdk8
    - script:
      - ./.travis.oraclejdk11-test.sh oraclejdk8

