language: groovy
before_install:
 - chmod +x ./gradlew
 - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && chmod +x ./install-jdk.sh
branches:
  only:
    - master
    - develop
env:
  global:
    TRAVIS_ENV=true
jdk:
  - openjdk8
  - oraclejdk8
matrix:
  include:
    - script:
        - echo "test using JDK 8(OpenJDK)"
        - javac -version ; java -version
        - jdk_switcher use openjdk8
        - javac -version ; java -version
        - ./gradlew check --stacktrace --info
    - script:
        - echo "test using JDK 9(OpenJDK)"
        - javac -version ; java -version
        - ./install-jdk.sh -F 9         && ./gradlew check --stacktrace --info
        - javac -version ; java -version
    - script:
        - echo "test using JDK 10(OpenJDK)"
        - javac -version ; java -version
        - ./install-jdk.sh -F 10        && ./gradlew check --stacktrace --info
        - javac -version ; java -version
    - script:
        - echo "test using JDK 11(OpenJDK)"
        - javac -version ; java -version
        - ./install-jdk.sh -F 11        && ./gradlew check --stacktrace --info
        - javac -version ; java -version
    - script:
        - echo "test using JDK 8(OracleJDK)"
        - javac -version ; java -version
        - jdk_switcher use oraclejdk8
        - javac -version ; java -version
        - ./gradlew check --stacktrace --info
    - script:
        - echo "test using JDK 10(OracleJDK)"
        - javac -version ; java -version
        - ./install-jdk.sh -F 10 -L BCL && ./gradlew check --stacktrace --info
        - javac -version ; java -version
    - script:
        - echo "test using JDK 11(OracleJDK)"
        - javac -version ; java -version
        - ./install-jdk.sh -F 11 -L BCL && ./gradlew check --stacktrace --info
        - javac -version ; java -version

