language: groovy
before_install:
 - chmod +x gradlew
 - chmod +x .test.sh
branches:
  only:
    - master
    - develop
env:
  global:
    TRAVIS_ENV=true
script: ./.test.sh
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk11

